### ISSUE TITLE
Unsupported texture format error on Mac

### ISSUE THREAD

**Issue by hotpot** [uclagamelab/MeshCreator#2]
I get "Unsupported texture format - needs to be ARGB32, RGBA32, BGRA32, RGB24, Alpha8 or DXT" on my images and on the sample images when I try to use this in my project.

I am running Unity 4.2.1f on a Mac.

Works fine in a fresh project on PC. I appreciate that's not massively fair comparison. Is this known to work on Mac?

**Comment by tstefanich** [comment]
Sorry for the delay in response. We having been updating the mesh creator for version 5.4 and we are unable to reproduce this error if you do have an image you can share with us to test that would be great.
