### ISSUE TITLE
Can't make ObjectCompoundColliders accurately

### ISSUE THREAD

**Issue by kdxu** [uclagamelab/MeshCreator#3]
I got a message "Mesh Creator: yikes, got a negative box inside pixel map array. Try resaving the image. Please create a new issue at https://github.com/uclagamelab/MeshCreator/issues." and I could not find find "ObjectCompoundColliders" of my created Mesh Object.
I am running Unity 4.5.4f1 on a Mac.

**Comment by jonathandcecil** [comment]
Could you please attach the image you were trying to use? If you don't want that public, maybe you email it to me at jonathancecil@arts.ucla.edu
Thanks much.

**Comment by kdxu** [comment]
I send an email just now. Thanks.
