### ISSUE TITLE
Incompatibility with Unity3d 5.4

### ISSUE THREAD

**Issue by AndrewKeplinger** [uclagamelab/MeshCreator#4]
Throwing error when creating window due to changes in Unity3D 5.4:  100% reproducible.

Load is not allowed to be called from a ScriptableObject constructor (or instance field initializer), call it in OnEnable instead. Called from ScriptableObject 'MeshCreatorWizard'.
See "Script Serialization" page in the Unity Manual for further details.
UnityEngine.Resources:Load(String)
MeshCreatorWizard:.ctor()
UnityEditor.EditorWindow:GetWindow(Type, Boolean, String)
MeshCreatorWizard:Init() (at Assets/UCLAGameLab/Editor/MeshCreatorWizard.cs:71)

It appears that changes in initialization of Editor windows requires either a fix from Unity3D or modification to Mesh Creator code.

**Comment by jonathandcecil** [comment]
Version 0.8 now supports up to Unity 5.5. Thanks for letting us know, this got the ball rolling.
